apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-oscar
spec:
  replicas: 4
  selector:
    matchLabels:
      role: redoscar
  template:
    metadata:
      labels:
        role: redoscar
    spec:
      containers:
        - name: container-iris
          image: paule.azurecr.io/modelo-oscar:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: oscar

---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 8000
  selector:
    role: redoscar